# examples of command line use
# rosparam load ./stretch_marker_dict.yaml
# rosparam list
# rosparam get /aruco_markers/

# Be careful with length_mm values. Stickers and printouts can vary
# significantly from your expectations. You should measure them
# directly. For example, in a prototype robot the stickers were closer
# to 23mm wide than 24mm. This 1mm difference resulted in > 1cm of
# error in the depths for the marker pose estimates when only using
# RGB images.


'aruco_marker_info': 
  '0':
    'length_mm': 47
    'use_rgb_only': False
    'name': 'Object 1'
    'link': None
  'default':
    'length_mm': 24
    'use_rgb_only': False
    'name': 'unknown'
    'link': None
    